version: '2'

services:

  web:
    build: '.'
    image: 'brounder'
    # TODO COMPLETE THIS
  
  postgres:
    container_name: 'postgres'
    image: 'postgres:9.5.3'
    # TODO COMPLETE THIS
  
  redis:
    container_name: 'redis'
    image: 'redis:3.2.0'
    # TODO COMPLETE THIS
  
volumes:
  pgdata:
  redisdata:
  cachedata:
  mediadata: