apiVersion: apps/v1
kind: Deployment
metadata:
  name: brounder
  labels:
    name: brounder
spec:
  replicas: 1
  selector:
    matchLabels:
      name: brounder
  template:
    metadata:
      labels:
        name: brounder
    spec:
      containers:
      - name: brounder
        image: brounder:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: db-passwords

---

apiVersion: v1
kind: Service
metadata:
  name: brounder
  labels:
    name: brounder
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    name: brounder
